services:
  db:
    build: db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    networks:
      - back

  server:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMA: api
    depends_on:
      - db
    networks:
      - back
      - front

  # TODO enable service
  # frontend:
  #   build: frontend
  #   depends_on:
  #     - server
  #   networks:
  #     - front

networks:
  front: {}
  back: {}
